version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./test.db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
